### PR TITLE
fixed mail template for Magento 1.9.3.10

### PR DESCRIPTION
**Pull request by sprankhub**
See https://github.com/OpenMage/magento-mirror/commit/f1127a8d87117164bfaac8b76834829fe5f4720d#diff-65017e222819ad1ccc78ba33f2c4ed9d

### CODE REVIEW

**Comment by Schrank** [comment]
When I merge that, it doesn't work with any version prior 1.9.3.10.

**Comment by Schrank** [comment]
Any idea about that? @riconeitzel preview is always for the newest magento version, right? Then we can merge it :-)

**Comment by sprankhub** [comment]
True. Solution: Always use the latest version ;-)

I would also think that preview is always for the newest version. But finally, @riconeitzel must decide about that.

**Comment by riconeitzel** [comment]
current opinion: latest version = latest version

for further updates (still working on it) this version was thought to suit ALL magento versions since 1.0 :-/

well … go for it ¯\_(⊙︿⊙)_/¯

**Comment by Schrank** [comment]
🤷‍♂️ It is a preview. If people need 1.9.3.9 support, they need to fix the commit.

**Pull request merged**
